create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'rejected', 'blocked')),
  created_at timestamptz not null default now(),
  accepted_at timestamptz null
);

create unique index if not exists friendships_requester_addressee_unique_idx
on public.friendships (requester_id, addressee_id);

create index if not exists friendships_requester_idx
on public.friendships (requester_id);

create index if not exists friendships_addressee_idx
on public.friendships (addressee_id);
