-- ============================================================
-- White Christmas - Initial Schema
-- ============================================================

-- profiles: one row per user, stores their Fernet encryption key
-- key is generated by backend on first protect call
CREATE TABLE IF NOT EXISTS public.profiles (
    id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    fernet_key  TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- images: tracks every protected photo
-- image_id = 24-bit ID embedded in the watermark
CREATE TABLE IF NOT EXISTS public.images (
    image_id    BIGINT PRIMARY KEY,
    owner_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- permissions: which viewers can decrypt which images
CREATE TABLE IF NOT EXISTS public.permissions (
    image_id    BIGINT NOT NULL REFERENCES public.images(image_id) ON DELETE CASCADE,
    viewer_id   UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    granted_at  TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    PRIMARY KEY (image_id, viewer_id)
);

-- ============================================================
-- Row Level Security
-- ============================================================
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;

-- profiles: users can only read their own key
CREATE POLICY "users can view own profile"
    ON public.profiles FOR SELECT
    USING (auth.uid() = id);

-- images: owner can insert, anyone can view (image_id is not sensitive)
CREATE POLICY "owner can insert image"
    ON public.images FOR INSERT
    WITH CHECK (auth.uid() = owner_id);

CREATE POLICY "anyone can view images"
    ON public.images FOR SELECT
    USING (true);

-- permissions: owner can grant, viewer can see their own permissions
CREATE POLICY "owner can grant permission"
    ON public.permissions FOR INSERT
    WITH CHECK (
        auth.uid() = (
            SELECT owner_id FROM public.images WHERE image_id = permissions.image_id
        )
    );

CREATE POLICY "viewer can see own permissions"
    ON public.permissions FOR SELECT
    USING (auth.uid() = viewer_id);
